[2024-09-03T17:43:52.207+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:43:52.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:43:52.213+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:43:52.212+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:43:55.592+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:43:55.589+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:43:55.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:43:55.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 3.456 seconds
[2024-09-03T17:44:26.183+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:26.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:44:26.191+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:26.191+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:26.829+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:26.825+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:44:26.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:26.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.742 seconds
[2024-09-03T17:44:57.405+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:57.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:44:57.409+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:57.409+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:58.162+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:58.157+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:44:58.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:44:58.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.854 seconds
[2024-09-03T17:45:28.760+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:45:28.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:45:28.768+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:28.765+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:45:29.478+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:29.475+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:45:29.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:45:29.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.779 seconds
[2024-09-03T17:46:00.053+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:00.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:46:00.057+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:00.057+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:00.746+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:00.742+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:46:00.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:00.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.768 seconds
[2024-09-03T17:46:31.378+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:31.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:46:31.382+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:31.381+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:32.083+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:32.078+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:46:32.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:46:32.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.791 seconds
[2024-09-03T17:47:02.635+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:02.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:47:02.638+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:02.638+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:03.200+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:03.196+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:47:03.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:03.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.639 seconds
[2024-09-03T17:47:33.438+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:33.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:47:33.441+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:33.441+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:33.990+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:33.986+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:47:33.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:47:34.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.625 seconds
[2024-09-03T17:48:04.391+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:04.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:48:04.394+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:04.394+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:05.012+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:05.008+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:48:05.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:05.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.698 seconds
[2024-09-03T17:48:35.648+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:35.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:48:35.652+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:35.651+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:36.167+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:36.161+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:48:36.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:48:36.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.579 seconds
[2024-09-03T17:49:06.509+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:06.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:49:06.513+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:06.513+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:07.157+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:07.153+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:49:07.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:07.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.761 seconds
[2024-09-03T17:49:37.785+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:37.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:49:37.788+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:37.788+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:38.452+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:38.448+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:49:38.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:49:38.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.733 seconds
[2024-09-03T17:50:09.065+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:09.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:50:09.069+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:09.068+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:09.653+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:09.648+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:50:09.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:09.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.659 seconds
[2024-09-03T17:50:40.051+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:40.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:50:40.056+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:40.055+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:40.713+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:40.709+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:50:40.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:50:40.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.729 seconds
[2024-09-03T17:51:10.911+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:10.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:51:10.915+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:10.915+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:11.571+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:11.566+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:51:11.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:11.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.783 seconds
[2024-09-03T17:51:42.239+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:42.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:51:42.242+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:42.242+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:42.810+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:42.804+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:51:42.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:51:42.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.629 seconds
[2024-09-03T17:52:13.127+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:13.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:52:13.131+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:13.131+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:13.698+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:13.693+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:52:13.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:13.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.642 seconds
[2024-09-03T17:52:43.855+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:43.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:52:43.858+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:43.858+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:44.405+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:44.401+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:52:44.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:52:44.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.627 seconds
[2024-09-03T17:53:15.067+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:15.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:53:15.071+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:15.070+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:15.765+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:15.761+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:53:15.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:15.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.770 seconds
[2024-09-03T17:53:46.322+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:46.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:53:46.327+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:46.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:46.978+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:46.974+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:53:46.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:53:47.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.734 seconds
[2024-09-03T17:54:17.619+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:17.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:54:17.624+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:17.624+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:18.244+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:18.239+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:54:18.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:18.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.734 seconds
[2024-09-03T17:54:49.052+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:49.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:54:49.064+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:49.063+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:49.869+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:49.864+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:54:49.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:54:49.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.888 seconds
[2024-09-03T17:55:20.579+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:20.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:55:20.583+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:20.583+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:21.160+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:21.154+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:55:21.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:21.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.645 seconds
[2024-09-03T17:55:51.347+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:51.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:55:51.351+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:51.351+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:51.942+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:51.938+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:55:51.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:55:51.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.659 seconds
[2024-09-03T17:56:22.491+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:22.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:56:22.495+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:22.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:23.170+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:23.167+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:56:23.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:23.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.747 seconds
[2024-09-03T17:56:53.915+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:53.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:56:53.920+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:53.920+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:54.491+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:54.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:56:54.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:56:54.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.649 seconds
[2024-09-03T17:57:24.939+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:24.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:57:24.943+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:24.942+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:25.585+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:25.581+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:57:25.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:25.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.732 seconds
[2024-09-03T17:57:55.815+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:55.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:57:55.819+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:55.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:56.399+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:56.395+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:57:56.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:57:56.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.650 seconds
[2024-09-03T17:58:27.339+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:27.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:58:27.345+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:27.344+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:28.060+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:28.056+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:58:28.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:28.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.793 seconds
[2024-09-03T17:58:58.854+0000] {processor.py:186} INFO - Started process (PID=652) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:58.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:58:58.858+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:58.858+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:59.511+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:59.507+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:58:59.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:58:59.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.719 seconds
[2024-09-03T17:59:29.754+0000] {processor.py:186} INFO - Started process (PID=668) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T17:59:29.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T17:59:29.758+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:29.758+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T17:59:30.339+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:30.336+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:59:30.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T17:59:30.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.657 seconds
[2024-09-03T18:00:01.109+0000] {processor.py:186} INFO - Started process (PID=684) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:01.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:00:01.113+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:01.113+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:01.570+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:01.565+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:00:01.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:01.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.542 seconds
[2024-09-03T18:00:31.865+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:31.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:00:31.870+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:31.870+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:32.473+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:32.467+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:00:32.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:00:32.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.704 seconds
[2024-09-03T18:01:03.420+0000] {processor.py:186} INFO - Started process (PID=716) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:03.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:01:03.434+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:03.427+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:03.988+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:03.984+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:01:03.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:04.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.653 seconds
[2024-09-03T18:01:34.126+0000] {processor.py:186} INFO - Started process (PID=732) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:34.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:01:34.130+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:34.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:34.594+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:34.590+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:01:34.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:01:34.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.539 seconds
[2024-09-03T18:02:05.152+0000] {processor.py:186} INFO - Started process (PID=748) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:05.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:02:05.156+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:05.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:05.656+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:05.653+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:02:05.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:05.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.578 seconds
[2024-09-03T18:02:35.870+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:35.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:02:35.875+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:35.875+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:36.357+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:36.352+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:02:36.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:02:36.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.573 seconds
[2024-09-03T18:03:07.152+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:07.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:03:07.156+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:07.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:07.598+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:07.593+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:03:07.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:07.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.567 seconds
[2024-09-03T18:03:37.793+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:37.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:03:37.797+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:37.797+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:38.287+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:38.284+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:03:38.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:03:38.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.564 seconds
[2024-09-03T18:04:09.280+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:09.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:04:09.285+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:09.284+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:09.702+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:09.697+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:04:09.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:09.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.486 seconds
[2024-09-03T18:04:39.830+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:39.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:04:39.834+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:39.833+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:40.267+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:40.263+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:04:40.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:04:40.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.574 seconds
[2024-09-03T18:05:11.300+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:11.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:05:11.304+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:11.304+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:11.730+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:11.727+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:05:11.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:11.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.495 seconds
[2024-09-03T18:05:42.594+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:42.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:05:42.598+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:42.598+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:43.139+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:43.135+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:05:43.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:05:43.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.624 seconds
[2024-09-03T18:06:13.267+0000] {processor.py:186} INFO - Started process (PID=876) to work on /opt/airflow/dags/example_dag.py
[2024-09-03T18:06:13.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-09-03T18:06:13.272+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:06:13.271+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-09-03T18:06:13.769+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:06:13.765+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 11, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:06:13.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-09-03T18:06:13.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/example_dag.py took 0.576 seconds
